### ISSUE TITLE
Use with a self-hosted Bitwarden server

### ISSUE THREAD

**Issue by 7185** [RikudouSage/harbour-bitsailor#24]
This app looks great but I can't use it with my self-hosted server (vaultwarden).
Would it be possible to add a new form to do something like:
`bw config server https://your.bw.domain.com`?
Thank you

**Comment by RikudouSage** [comment]
Sure, I'll take a look at it during November.

**Comment by RikudouSage** [comment]
There's currently a bug in Bitwarden CLI where it doesn't return the current server, so there's no clean way of knowing if it has been changed. Is that acceptable?

**Comment by 7185** [comment]
Yes of course, as long as the feature works, that's fine with me.
Also I tried to help with a French translation but couldn't access the transifex project, do you have to accept something?

**Comment by RikudouSage** [comment]
I think you have to ask to join the project and after that I have to accept the request. Did you ask to join already?

**Comment by 7185** [comment]
Yes I did

**Comment by RikudouSage** [comment]
I didn't get any notification but I've approved your request now manually.

**Comment by RikudouSage** [comment]
I've added the option to set custom URL, can you update the app on your phone and test it? I don't have a custom server and would like to avoid it just for the sake of testing.

**Comment by 7185** [comment]
Thank you, it worked!
I needed to wait for about 20-30 seconds, then go back to the main page and manually log out and then I could log in on my custom server.

**Comment by RikudouSage** [comment]
I will make the process better in the next version, currently working on making it accessible on the login screen. Let me know if you encounter any problem!

**Comment by RikudouSage** [comment]
It should be now available on the login screen. Closing this issue, please reopen in case something doesn't work as expected.
